---

- name: gather os specific variables
  include_vars: 
    file: "{{ ansible_os_family | os_family_to_os_type }}.yml"
  ignore_errors: yes

- name: track versions
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-track-versions.yml"
  when: state|default('present') == 'present' and ansible_os_family == "Darwin" and mac_version == "10.14"

- name: install
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-install.yml"
  when: state|default('present') == 'present' and ansible_os_family == "Darwin" and mac_version == "10.14"


