---

- name: validate vars
  include_tasks: tasks/variables.yml
  when: ansible_os_family == "Darwin"

- name: track versions
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-track-versions.yml"
  when: 
    - state|default('present') == 'present' 
    - ansible_os_family == "Darwin"
    - mac_version == "10.14" or mac_version == "10.15" or mac_version == "11.1"

- name: install
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-install.yml"
  when: 
    - state|default('present') == 'present' 
    - ansible_os_family == "Darwin"
    - mac_version == "10.14" or mac_version == "10.15" or mac_version == "11.1"

- name: uninstall
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-uninstall.yml"
  when: 
    - state|default('present') == 'absent' 
    - ansible_os_family == "Darwin"
